---
collections:
  - name: community.general
    version: ">=7.0.0"
  - name: community.proxmox
    version: ">=1.0.0"

roles:
  - name: lablabs.rke2
    src: https://github.com/lablabs/ansible-role-rke2

