---
# This file contains a simpler version of VM cloning task
# that can be included directly if needed

- name: Clone VM from template
  become: false
  community.proxmox.proxmox_kvm:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ vault_proxmox_api_token_id }}"
    api_token_secret: "{{ vault_proxmox_api_token_secret }}"
    node: "{{ proxmox_node }}"
    clone: "{{ proxmox_template_id }}"
    vmid: "{{ vm_id }}"
    name: "{{ vm_name }}"
    storage: "{{ vm_storage }}"
    full: true
    timeout: "{{ vm_timeout }}"

    # ✅ Cloud-Init DNS settings (plural)
    nameservers: "{{ vm_nameservers | default(['1.1.1.1','8.8.8.8']) }}"
    searchdomains: "{{ vm_searchdomains | default([]) }}"

    # ✅ Cloud-Init user settings (scalars)
    ciuser: "{{ vm_ciuser }}"
    cipassword: "{{ vm_cipassword }}"
    sshkeys: "{{ vm_sshkeys }}"        # string with one or more public keys (newline-separated)

    # Optional: only if your template lacks a cloud-init disk
    # ide:
    #   ide2: "local:cloudinit,format=qcow2"

  delegate_to: localhost

