---
- name: Create systemd service file for Semaphore
  ansible.builtin.template:
    src: semaphore.service.j2
    dest: /etc/systemd/system/semaphore.service
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable Semaphore service
  ansible.builtin.systemd:
    name: semaphore
    enabled: "{{ semaphore_service_enabled }}"
    state: stopped
