---
- name: Ensure MySQL is running
  ansible.builtin.systemd:
    name: mysql
    state: started

- name: Wait for MySQL to be ready
  ansible.builtin.wait_for:
    port: 3306
    host: "{{ semaphore_db_host }}"
    delay: 5
    timeout: 30

- name: Test database connection
  ansible.builtin.mysql_db:
    name: "{{ semaphore_db_name }}"
    state: present
    login_host: "{{ semaphore_db_host }}"
    login_port: "{{ semaphore_db_port }}"
    login_user: "{{ semaphore_db_user }}"
    login_password: "{{ semaphore_db_password }}"
